spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Quiz-Engine-Service
          uri: lb:http://QUIZ-ENGINE-SERVICE
          predicates:
            - Path=/quiz/**
        - id: Question-Bank-Service
          uri: lb:http://QUESTION-BANK-SERVICE
          predicates:
            - Path=/question/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true